class ACEStrings {
  static const sex = ['Male', 'Female', 'Non-Binary'];
  static const ages = [
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '26',
    '27',
    '28',
    '29',
    '30',
    '31',
    '32',
    '33',
    '34',
    '35',
    '36',
    '37',
    '38',
    '39',
    '40',
    '41',
    '42',
    '43',
    '44',
    '45',
    '46',
    '47',
    '48',
    '49',
    '50',
  ];
  static const dept = [
    'CAS - College of Arts and Sciences',
    'CAHS - College of Allied Health Sciences',
    'CEA - College of Engineering and Architecture',
    'CELA - College of Education Liberal Arts',
    'CCJE - College of Criminal Justice Education',
    'CMA - College of Management and Accountancy',
    'CITE - College of Information Technology Education',
    'Null',
  ];
}
